Repository dbinfrago/capellambse-context-diagrams, pull requests merged in 2024-06, with the labels that each got.

#99 refactor: Better code
  capellambse_context_diagrams/_elkjs.py
  capellambse_context_diagrams/collectors/default.py
  capellambse_context_diagrams/context.py
Labels: enhancement

#105 fix: Fix walrus in context
  capellambse_context_diagrams/context.py
Labels: bug

#106 fix(realization-view): Fix broken styleclass for edges
  capellambse_context_diagrams/context.py
  capellambse_context_diagrams/serializers.py
  tests/test_context_diagrams.py
Labels: bug

#110 fix(context-diagram): Make port processing more secure
  capellambse_context_diagrams/collectors/default.py
Labels: bug

#113 feat: Feat-hide-functions
  capellambse_context_diagrams/collectors/exchanges.py
  capellambse_context_diagrams/context.py
  docs/gen_images.py
  docs/index.md
  docs/interface.md
  mkdocs.yml
  tests/test_interface_diagrams.py
Labels: documentation, enhancement
